---
params:
  first_name: "Andrew"
  last_name: "Belen"
author:
- Prof Frink
opening: Dear `r params$first_name` `r params$last_name`,
closing: Sincerely,
return-address: 
- 456 Road St.
- Springfield, NY
output: linl::linl
graphics: yes
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
	fig.retina = 2,
	message = FALSE,
	warning = FALSE,
	echo=FALSE
)
library(tidyverse)
library(here)

df <- read_csv(here::here("data", "joined.csv")) 

filtered_df <- df %>% 
  filter(first_name==params$first_name & last_name ==params$last_name) 

score1 <- filtered_df %>% 
  .$`First Score`

score2 <- filtered_df %>% 
  .$`Second Score`

pgender <- filtered_df %>% 
  .$gender

page <- filtered_df %>% 
  .$age
```


Here is the results of your test. Your first score was `r score1` and your second score was `r score2`.

Here is how you compare for people of the same age and gender:

```{r}
bind_rows("Age and Gender Matched" = 
df %>% filter(age==page & gender==pgender) %>% 
  summarise(score1 = mean(`First Score`),
            score2 = mean(`Second Score`)) %>% 
  pivot_longer(everything(), names_to = "Test"),
"You" = list(Test = c("score1","score2"), value=c(score1, score2)),
.id="id") %>% 
  ggplot(aes(x=Test,y=value, fill=id)) + 
  geom_col(position="dodge") + 
  theme_minimal() + 
  labs(x="Test",
       y="Score",
       title = paste("Scores for",params$first_name, params$last_name)) + 
  theme(legend.title= element_blank(),
        legend.position="bottom")
```

Yardy yardy yarda.
